### PR TITLE
Stops runtime error in IE6+

### PR DESCRIPTION
**Pull request by coldclimate**
Hi,
I kept getting runtime errors with IE6 (and 8) until i switched the p for a div.  Not tested hard.

### CODE REVIEW

**Comment by honza** [comment]
See, the `<div/>` element is a general purpose HTML element that can hold anything in it. This is in sharp contrast to the paragraph tag which is only meant to be used for copy text that will actually be displayed.

While I certainly appreciate your effort to fix this framework in IE, I don't think this is the right approach.

**Comment by coldclimate** [comment]
No worries - I'm not big into IE support but needed to make it work (if not in a nice way).

**Comment by honza** [comment]
As [Kenneth Reitz](https://github.com/kennethreitz) would say, "It came out 11 years ago. That's older than Youtube. Upgrade."

**Comment by coldclimate** [comment]
I wish I could in this case.  Developing things other people run on their domains is a PITA.

**Comment by coldclimate** [comment]
(oh and thanks for the reference I've been trying to dig that up for months)

**Comment by honza** [comment]
Haha, here is where I happened first.

https://github.com/kennethreitz/requests/issues/351#issuecomment-3439382

**Pull request closed without merging**
